# Generated by Django 2.1.7 on 2019-03-02 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'employé")),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'entreprise")),
            ],
        ),
        migrations.AddField(
            model_name='employe',
            name='entreprise',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='EntrepriseManager.Entreprise'),
        ),
    ]
