# Generated by Django 2.1.7 on 2019-03-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='datecreation',
            field=models.DateField(null=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='entreprise',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='EntrepriseManager.Entreprise'),
        ),
    ]
