# Generated by Django 2.1.7 on 2019-03-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseManager', '0002_auto_20190302_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='entreprise',
        ),
        migrations.DeleteModel(
            name='Employe',
        ),
    ]
