# Generated by Django 2.1.7 on 2019-03-03 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseManager', '0003_auto_20190303_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'employé")),
                ('entreprise', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='EntrepriseManager.Entreprise')),
            ],
        ),
    ]
