# Generated by Django 2.1.7 on 2019-03-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseManager', '0004_employe'),
    ]

    operations = [
        migrations.CreateModel(
            name='AH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Ceci_est_un_test',
            },
        ),
    ]
