# Generated by Django 2.1.7 on 2019-03-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseManager', '0005_ah'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AH',
        ),
    ]
